### Set up PyTorch and Cuda

In [14]:
# the command below displays the current status and information of NVIDIA GPUs installed on the system
!nvidia-smi

Wed Jun  7 16:12:47 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.105.01   Driver Version: 515.105.01   CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   39C    P8    12W /  N/A |    897MiB /  8192MiB |     38%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

On my computer, it shows that I have an NVIDIA GPU installed. Try on your own computer, if you have NVIDIA GPU, it will work without problem.

In [15]:
import torch

#Check if the GPU is available with PyTorch.
torch.cuda.is_available()

True

In [16]:
# count nomber of device 
torch.cuda.device_count()

1

:abacus: Counting the number of available GPUs, if we have more than 2, we can assign each GPU to different computations to achieve faster processing. Unfortunately, I only have 1 GPU. 

In [10]:
# As we metionned about device. It is mandatory for all tensors to have the same device to avoid errors when running your code
# So we have cuda available it will perfom the computation only on NVIDIA GPU. Otherwise, it will work on cpu
device ="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

For more details about setting up device, please refer to the [documentation](https://pytorch.org/docs/stable/notes/cuda.html)

The question :monocle_face: is how we will put tensors and models on the GPU?

In [7]:
# let's create a tensor 
tensor= torch.arange(10,16)

print(tensor,tensor.device)
# by default is cpu

tensor([10, 11, 12, 13, 14, 15]) cpu


By defaut, tensors perform on CPU 

In [19]:
#To move tensors to GPU, of course if it is available 

tensor_cpu_to_gpu = tensor.to(device)
tensor_cpu_to_gpu

tensor([10, 11, 12, 13, 14, 15], device='cuda:0')

> :bulb:Note : If the device doesn't have a GPU, it will fall back to using the CPU, as defined by the device variable above

In [18]:
# Try to uncomment and figure out what is the problem

#tensor_cpu_to_gpu.numpy()


In [20]:
# if we need to come back to work with numpy, we need to disable the GPU 
tensor_gpu_to_cpu=tensor_cpu_to_gpu.cpu().numpy()
tensor_gpu_to_cpu

array([10, 11, 12, 13, 14, 15])