### Reproducibility

In [3]:
import torch

# Create two random tensors
tensor_random_1 = torch.rand(5, 4)
print("Tensor 1 =\n",tensor_random_1)
print("")
tensor_random_2 = torch.rand(5, 4)
print("Tensor 2 =\n",tensor_random_2)

Tensor 1 =
 tensor([[0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447],
        [0.5315, 0.1587, 0.6542, 0.3278],
        [0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666]])

Tensor 2 =
 tensor([[0.9811, 0.0874, 0.0041, 0.1088],
        [0.1637, 0.7025, 0.6790, 0.9155],
        [0.2418, 0.1591, 0.7653, 0.2979],
        [0.8035, 0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057, 0.3725]])


we could verify if tensor 1 is equal to tensor 2. But, i don't think so :smile:

In [4]:
tensor_random_1 == tensor_random_2

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [6]:
# Set the random seed
seed=42 # You can choose any number you want; 42 is just one we often see in examples.

> Note : you have to reset the seed every time a new rand() is called 

In [8]:
# set the random seed for the PyTorch library
torch.manual_seed(seed=seed) 
tensor_random_3 = torch.rand(5, 4)
print("Tensor 3 =\n",tensor_random_3)


torch.random.manual_seed(seed=seed) 
tensor_random_4 = torch.rand(5, 4)
print("Tensor 4 =\n",tensor_random_4)


Tensor 3 =
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274]])
Tensor 4 =
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274]])


Tensor 3 sould be  equal to Tensor 4 :smile:

try to comment out one of the line **"torch.random.manual_seed(seed=seed)"** and run the code. What can you say ?